<a href="https://colab.research.google.com/github/ismarnetodev/WorkshopDados2025.2/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import pandas as pd

df = pd.read_csv("/content/sample_data/dados_nao_tratados.csv")

print(df.info())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              10 non-null     int64
 1   nome            10 non-null     object
 2   idade           9 non-null      object
 3   data_inscricao  9 non-null      object
 4   nota            8 non-null      object
 5   ativo           10 non-null     object
dtypes: int64(1), object(5)
memory usage: 612.0+ bytes
None
   id    nome         idade data_inscricao nota ativo
0   1     Ana            25     2023-05-12  8.5   Sim
1   2   Bruno  vinte e três     2023/13/01  9.0  TRUE
2   3   Carla            30            NaN  NaN   Não
3   4  Daniel           NaN     2022-07-15  7.2   sim
4   5   Érica            27     2022-08-XX    8     e

In [57]:

df["nota"] = pd.to_numeric(df["nota"], errors="coerce")
df["nota"] = df["nota"].fillna(df["nota"].mean())

df["idade"] = pd.to_numeric(df["idade"], errors="coerce")
df["idade"] = df["idade"].fillna(df["idade"].median())

In [58]:
df["ativo"] = df["ativo"].str.strip().str.lower()
df["ativo"] = df["ativo"].map({"sim": True, "não": False, "true": True, "e": False})

In [59]:
df["data_inscricao"] = pd.to_datetime(df["data_inscricao"], errors="coerce")

In [60]:
df = df.drop_duplicates()

In [61]:
df.rename(columns={
    "id": "id",
    "nome": "nome",
    "idade": "idade",
    "data_inscricao": "data_inscricao",
    "nota": "nota",
    "ativo": "ativo"
}, inplace=True)

In [62]:
df.to_csv("dados_tratados.csv", index=False)

In [63]:
df

   id       nome  idade data_inscricao       nota  ativo
0   1        Ana   25.0     2023-05-12   8.500000   True
1   2      Bruno   25.0            NaT   9.000000   True
2   3      Carla   30.0            NaT   8.414286  False
3   4     Daniel   25.0     2022-07-15   7.200000   True
4   5      Érica   27.0            NaT   8.000000  False
5   6  Francisco   29.0            NaT   8.414286    NaN
6   7   Gabriela   21.0     2023-01-05  10.000000   True
7   8   Henrique   19.0            NaT   9.500000    NaN
8   9      Ivana   11.0     2023-03-10   8.414286    NaN
9  10       José   25.0     2022-11-25   6.700000   True